# Generated by Django 6.0.7 on 2026-08-06 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('timeline', models.JSONField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['user', 'scheduled_for'], name='calendar_sc_user_id_15286d_idx'), models.Index(fields=['reminder_sent_at', 'scheduled_for'], name='calendar_sc_reminde_ebdbbf_idx')],
            },
        ),
    ]
