# Generated by Django 6.0.7 on 2026-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_rename_scheduled_for_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledplan',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
